print()
print("Please answer the following questions:")
print()
age = int(input("How old are you? "))
print(f"On your next birthday, you will be {age + 1}.")
print()
eggs = int(input("How many egg cartons do you have?"))
print(f"Your have {eggs * 12} eggs.")
print()
cookies = int(input("How many cookies do you have?"))
people = int(input("How many people are there?"))
print()
cookies_per_person = cookies / people
print(f"Each person will have {cookies_per_person} cookies")
print()