print( "PLEASE ENTER THE FOLLOWING INFORMATION:")
print()
#I could also put \n instead of print()
first_name = input("FIRST NAME:")
last_name = input("LAST NAME:")
email = input("EMAIL ADRESS:")
phone_number = input("PHONE NUMBER:")
job_title = input("JOB TITLE:")
id = input("ID NUMBER:")
print()
print("THE ID CARD IS:")
print("------------------------------------")
print(f"{last_name.upper()}, {first_name}.")
print(f"{job_title.title()}")
print(f"ID: {id}")
print()
print(f"{email.lower()}")
print(f"{phone_number}")
print("------------------------------------")
#check :20s
#i could also put ("-"*30) instead of ----....
print()
