print()
print("Please enter the following information:")
print()
place = input("Place: ")
adjective = input("Adjective: ")
animal = input("Animal: ")
verb1 = input("Verb: ")
exclamation = input("Exclamation: ")
verb2 = input("Verb: ")
print()
print("Sam: - You know what just happened?")
print()
print(f"Sam: - I just came back from the {place} and I couldnt believe that I saw a {animal} {verb1}!!! In that moment I could only think - {exclamation}! - and I knew I had to {verb2} so that I would never forget that {adjective} experience and I could come and tell you about it.")
print("Sam: - What do you think?")